tbbc_rest_util:
    error:
        use_bundled_factories: true
        exception_mapping:
            FormErrorException:
                class: "Tbbc\\RestUtilBundle\\Error\\Exception\\FormErrorException"
                factory: tbbc_rest_util_form_error
                http_status_code: 400
                error_code: 400101
                error_message: "Invalid input"
                error_more_info_url: ~
            UnableToDeleteException:
                class: "Vlabs\\AddressBundle\\Exception\\UnableToDeleteException"
                factory: tbbc_rest_util_form_error
                http_status_code: 409
                error_code: 409101
                error_message: "Invalid input"
                error_more_info_url: ~