vlabs_address_get_cities:
    path: /cities
    defaults: { _controller: VlabsAddressBundle:Api/City:getCities }
    options:
        expose: true

vlabs_address_get_departments:
    path: /departments
    defaults: { _controller: AppBundle:Api\Department:getDepartments }
    methods: GET

vlabs_address_get_regions:
    path: /regions
    defaults: { _controller: VlabsAddressBundle:Api/Region:getRegions }
    methods: GET
