Vlabs\AddressBundle\Entity\Address:
    properties:
        street:
            - NotBlank: ~
            - NotNull: ~
        postcode:
            - NotBlank: ~
            - NotNull: ~
        city:
            - NotBlank: ~
            - NotNull: ~